name: Build Docker Image CI for Trello/Cue app

on:
  push:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/bergea1/trello-app:latest .
          docker push ghcr.io/bergea1/trello-app:latest
